---

# basic system tasks

- name: set locale to {{locale}}
  action: command /usr/sbin/update-locale LANG={{locale}} LC_ALL={{locale}}
  sudo: yes

- name: get r-server packages
  apt: name={{item}} state=latest install_recommends=yes update_cache=yes
  sudo: yes
  with_items:
    - build-essential
    - unzip
    - r-base
    - r-base-dev

- name: execute the R script to install packages
  shell: /usr/bin/Rscript --slave --no-save --no-restore-history /vagrant/r-requirements.R
  sudo: yes